// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

const listData = [
  {
    id: 1,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Louis Tomlinson",
    job: "Web Developer",
    location: "Jakarta",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "Louistommo@gmail.com",
      instagram: "@Louist91",
      github: "@Louistommo",
      gitlab: "@Louistommo91",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 2,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Fadly Syahroni",
    job: "Fullstack Developer",
    location: "Subang",
    skills: ["PHP", "JavaScript", "HTML", "CSS"],
    socmed: {
      email: "rayhangt89@gmail.com",
      instagram: "@Fadly81",
      github: "@Fadlysyah",
      gitlab: "@Fadlysyah81",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 3,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Indra Gunawan",
    job: "Front End Developer",
    location: "Subang",
    skills: ["PHP", "HTML", "CSS"],
    socmed: {
      email: "dragunawan@gmail.com",
      instagram: "@DraGunawan7",
      github: "@Indra7",
      gitlab: "@Indra7",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 4,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Arrois Addin",
    job: "Front End Developer",
    location: "Bandung",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "Roisaddin@gmail.com",
      instagram: "@Addin41",
      github: "@RoisAddin41",
      gitlab: "@RoisAddin41",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 5,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Sulaeman",
    job: "Back end Developer",
    location: "Jakarta",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "manajah7@gmail.com",
      instagram: "@Mann77",
      github: "@Sulaeman7",
      gitlab: "@Sulaeman77",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 6,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Kukuh Setiadi",
    job: "Fullstack Developer",
    location: "Bandung",
    skills: ["PHP", "JavaScript", "HTML", "CSS"],
    socmed: {
      email: "kukuhsetia5@gmail.com",
      instagram: "@Kuhsetya",
      github: "@KuhSetya5",
      gitlab: "@KuhSetya5",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 7,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Naufal Saputra",
    job: "Back end Developer",
    location: "Sumedang",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "naufalputra@gmail.com",
      instagram: "@opalputra",
      github: "@Naufal2",
      gitlab: "@Naufal2",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 8,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Tegar Maulana",
    job: "Web Developer",
    location: "Purwakarta",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "tegarmaulana@gmail.com",
      instagram: "@Tegarmaul",
      github: "@Tegaraja",
      gitlab: "@Tegaraja",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 9,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Muhammad Devandra",
    job: "Web Developer",
    location: "Lombok",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "devan@gmail.com",
      instagram: "@devvann",
      github: "@Devandra",
      gitlab: "@Devandra4",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 10,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Rizky Fadhilah",
    job: "Front end Developer",
    location: "Bandung",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "rizkyfadhilah@gmail.com",
      instagram: "@ikifadhilah",
      github: "@rizkyfad7",
      gitlab: "@rizkyfad7",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 11,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Khalil Ikhsan Qais",
    job: "Back end Developer",
    location: "Jakarta",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "Khalilqais@gmail.com",
      instagram: "@KhalilQais",
      github: "@KhalilQais",
      gitlab: "@KhalilQais",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 12,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Alfian Zen",
    job: "Back end Developer",
    location: "Surabaya",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "alfianzen@gmail.com",
      instagram: "@zenalfian",
      github: "@Alfian6",
      gitlab: "@Alfian6",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 13,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Cahya Purnama",
    job: "Front end Developer",
    location: "Solo",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "Cahyapur@gmail.com",
      instagram: "@Cahyana",
      github: "@Cahya9",
      gitlab: "@Cahya9",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 14,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Johan Iskandar",
    job: "Fullstack Developer",
    location: "Magelang",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "Jojoiskandar@gmail.com",
      instagram: "@JohanIskandar",
      github: "@Johaniskandar3",
      gitlab: "@Johaniskandar3",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
  {
    id: 15,
    photo: `https://i.pravatar.cc/150?u=${new Date().getTime()}`,
    fullname: "Dedi kusnaedi",
    job: "Mobile Developer",
    location: "Bengkulu",
    skills: ["PHP", "JavaScript", "HTML"],
    socmed: {
      email: "Dedikusnaedi@gmail.com",
      instagram: "@Kusnaedi7",
      github: "@DediKusnaedi",
      gitlab: "@DediKusnaedi7",
    },
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum erat orci, mollis nec gravida sed, ornare quis urna. Curabitur eu lacus fringilla, vestibulum risus at.",
  },
];

export default function handler(req, res) {
  if (req.query.id) {
    res.status(200).json({
      status: true,
      message: "Get data success",
      data: listData?.find((item) => item?.id === parseInt(req.query.id)),
    });
  } else {
    res
      .status(200)
      .json({ status: true, message: "Get data success", data: listData });
  }
}
